<?php
return [
    'province' => [
        [
            'id'        => 2,
            'parent_id' => 1,
            'name'      => '北京',
            'type'      => 1,
        ],
        [
            'id'        => 3,
            'parent_id' => 1,
            'name'      => '安徽',
            'type'      => 1,
        ],
        [
            'id'        => 4,
            'parent_id' => 1,
            'name'      => '福建',
            'type'      => 1,
        ],
        [
            'id'        => 5,
            'parent_id' => 1,
            'name'      => '甘肃',
            'type'      => 1,
        ],
        [
            'id'        => 6,
            'parent_id' => 1,
            'name'      => '广东',
            'type'      => 1,
        ],
        [
            'id'        => 7,
            'parent_id' => 1,
            'name'      => '广西',
            'type'      => 1,
        ],
        [
            'id'        => 8,
            'parent_id' => 1,
            'name'      => '贵州',
            'type'      => 1,
        ],
        [
            'id'        => 9,
            'parent_id' => 1,
            'name'      => '海南',
            'type'      => 1,
        ],
        [
            'id'        => 10,
            'parent_id' => 1,
            'name'      => '河北',
            'type'      => 1,
        ],
        [
            'id'        => 11,
            'parent_id' => 1,
            'name'      => '河南',
            'type'      => 1,
        ],
        [
            'id'        => 12,
            'parent_id' => 1,
            'name'      => '黑龙江',
            'type'      => 1,
        ],
        [
            'id'        => 13,
            'parent_id' => 1,
            'name'      => '湖北',
            'type'      => 1,
        ],
        [
            'id'        => 14,
            'parent_id' => 1,
            'name'      => '湖南',
            'type'      => 1,
        ],
        [
            'id'        => 15,
            'parent_id' => 1,
            'name'      => '吉林',
            'type'      => 1,
        ],
        [
            'id'        => 16,
            'parent_id' => 1,
            'name'      => '江苏',
            'type'      => 1,
        ],
        [
            'id'        => 17,
            'parent_id' => 1,
            'name'      => '江西',
            'type'      => 1,
        ],
        [
            'id'        => 18,
            'parent_id' => 1,
            'name'      => '辽宁',
            'type'      => 1,
        ],
        [
            'id'        => 19,
            'parent_id' => 1,
            'name'      => '内蒙古',
            'type'      => 1,
        ],
        [
            'id'        => 20,
            'parent_id' => 1,
            'name'      => '宁夏',
            'type'      => 1,
        ],
        [
            'id'        => 21,
            'parent_id' => 1,
            'name'      => '青海',
            'type'      => 1,
        ],
        [
            'id'        => 22,
            'parent_id' => 1,
            'name'      => '山东',
            'type'      => 1,
        ],
        [
            'id'        => 23,
            'parent_id' => 1,
            'name'      => '山西',
            'type'      => 1,
        ],
        [
            'id'        => 24,
            'parent_id' => 1,
            'name'      => '陕西',
            'type'      => 1,
        ],
        [
            'id'        => 25,
            'parent_id' => 1,
            'name'      => '上海',
            'type'      => 1,
        ],
        [
            'id'        => 26,
            'parent_id' => 1,
            'name'      => '四川',
            'type'      => 1,
        ],
        [
            'id'        => 27,
            'parent_id' => 1,
            'name'      => '天津',
            'type'      => 1,
        ],
        [
            'id'        => 28,
            'parent_id' => 1,
            'name'      => '西藏',
            'type'      => 1,
        ],
        [
            'id'        => 29,
            'parent_id' => 1,
            'name'      => '新疆',
            'type'      => 1,
        ],
        [
            'id'        => 30,
            'parent_id' => 1,
            'name'      => '云南',
            'type'      => 1,
        ],
        [
            'id'        => 31,
            'parent_id' => 1,
            'name'      => '浙江',
            'type'      => 1,
        ],
        [
            'id'        => 32,
            'parent_id' => 1,
            'name'      => '重庆',
            'type'      => 1,
        ],
        [
            'id'        => 33,
            'parent_id' => 1,
            'name'      => '香港',
            'type'      => 1,
        ],
        [
            'id'        => 34,
            'parent_id' => 1,
            'name'      => '澳门',
            'type'      => 1,
        ],
        [
            'id'        => 35,
            'parent_id' => 1,
            'name'      => '台湾',
            'type'      => 1,
        ],
    ],
    'city'     => [
        [
            'id'        => 36,
            'parent_id' => 3,
            'name'      => '安庆',
            'type'      => 2,
        ],
        [
            'id'        => 37,
            'parent_id' => 3,
            'name'      => '蚌埠',
            'type'      => 2,
        ],
        [
            'id'        => 38,
            'parent_id' => 3,
            'name'      => '巢湖',
            'type'      => 2,
        ],
        [
            'id'        => 39,
            'parent_id' => 3,
            'name'      => '池州',
            'type'      => 2,
        ],
        [
            'id'        => 40,
            'parent_id' => 3,
            'name'      => '滁州',
            'type'      => 2,
        ],
        [
            'id'        => 41,
            'parent_id' => 3,
            'name'      => '阜阳',
            'type'      => 2,
        ],
        [
            'id'        => 42,
            'parent_id' => 3,
            'name'      => '淮北',
            'type'      => 2,
        ],
        [
            'id'        => 43,
            'parent_id' => 3,
            'name'      => '淮南',
            'type'      => 2,
        ],
        [
            'id'        => 44,
            'parent_id' => 3,
            'name'      => '黄山',
            'type'      => 2,
        ],
        [
            'id'        => 45,
            'parent_id' => 3,
            'name'      => '六安',
            'type'      => 2,
        ],
        [
            'id'        => 46,
            'parent_id' => 3,
            'name'      => '马鞍山',
            'type'      => 2,
        ],
        [
            'id'        => 47,
            'parent_id' => 3,
            'name'      => '宿州',
            'type'      => 2,
        ],
        [
            'id'        => 48,
            'parent_id' => 3,
            'name'      => '铜陵',
            'type'      => 2,
        ],
        [
            'id'        => 49,
            'parent_id' => 3,
            'name'      => '芜湖',
            'type'      => 2,
        ],
        [
            'id'        => 50,
            'parent_id' => 3,
            'name'      => '宣城',
            'type'      => 2,
        ],
        [
            'id'        => 51,
            'parent_id' => 3,
            'name'      => '亳州',
            'type'      => 2,
        ],
        [
            'id'        => 52,
            'parent_id' => 2,
            'name'      => '北京',
            'type'      => 2,
        ],
        [
            'id'        => 53,
            'parent_id' => 4,
            'name'      => '福州',
            'type'      => 2,
        ],
        [
            'id'        => 54,
            'parent_id' => 4,
            'name'      => '龙岩',
            'type'      => 2,
        ],
        [
            'id'        => 55,
            'parent_id' => 4,
            'name'      => '南平',
            'type'      => 2,
        ],
        [
            'id'        => 56,
            'parent_id' => 4,
            'name'      => '宁德',
            'type'      => 2,
        ],
        [
            'id'        => 57,
            'parent_id' => 4,
            'name'      => '莆田',
            'type'      => 2,
        ],
        [
            'id'        => 58,
            'parent_id' => 4,
            'name'      => '泉州',
            'type'      => 2,
        ],
        [
            'id'        => 59,
            'parent_id' => 4,
            'name'      => '三明',
            'type'      => 2,
        ],
        [
            'id'        => 60,
            'parent_id' => 4,
            'name'      => '厦门',
            'type'      => 2,
        ],
        [
            'id'        => 61,
            'parent_id' => 4,
            'name'      => '漳州',
            'type'      => 2,
        ],
        [
            'id'        => 62,
            'parent_id' => 5,
            'name'      => '兰州',
            'type'      => 2,
        ],
        [
            'id'        => 63,
            'parent_id' => 5,
            'name'      => '白银',
            'type'      => 2,
        ],
        [
            'id'        => 64,
            'parent_id' => 5,
            'name'      => '定西',
            'type'      => 2,
        ],
        [
            'id'        => 65,
            'parent_id' => 5,
            'name'      => '甘南',
            'type'      => 2,
        ],
        [
            'id'        => 66,
            'parent_id' => 5,
            'name'      => '嘉峪关',
            'type'      => 2,
        ],
        [
            'id'        => 67,
            'parent_id' => 5,
            'name'      => '金昌',
            'type'      => 2,
        ],
        [
            'id'        => 68,
            'parent_id' => 5,
            'name'      => '酒泉',
            'type'      => 2,
        ],
        [
            'id'        => 69,
            'parent_id' => 5,
            'name'      => '临夏',
            'type'      => 2,
        ],
        [
            'id'        => 70,
            'parent_id' => 5,
            'name'      => '陇南',
            'type'      => 2,
        ],
        [
            'id'        => 71,
            'parent_id' => 5,
            'name'      => '平凉',
            'type'      => 2,
        ],
        [
            'id'        => 72,
            'parent_id' => 5,
            'name'      => '庆阳',
            'type'      => 2,
        ],
        [
            'id'        => 73,
            'parent_id' => 5,
            'name'      => '天水',
            'type'      => 2,
        ],
        [
            'id'        => 74,
            'parent_id' => 5,
            'name'      => '武威',
            'type'      => 2,
        ],
        [
            'id'        => 75,
            'parent_id' => 5,
            'name'      => '张掖',
            'type'      => 2,
        ],
        [
            'id'        => 76,
            'parent_id' => 6,
            'name'      => '广州',
            'type'      => 2,
        ],
        [
            'id'        => 77,
            'parent_id' => 6,
            'name'      => '深圳',
            'type'      => 2,
        ],
        [
            'id'        => 78,
            'parent_id' => 6,
            'name'      => '潮州',
            'type'      => 2,
        ],
        [
            'id'        => 79,
            'parent_id' => 6,
            'name'      => '东莞',
            'type'      => 2,
        ],
        [
            'id'        => 80,
            'parent_id' => 6,
            'name'      => '佛山',
            'type'      => 2,
        ],
        [
            'id'        => 81,
            'parent_id' => 6,
            'name'      => '河源',
            'type'      => 2,
        ],
        [
            'id'        => 82,
            'parent_id' => 6,
            'name'      => '惠州',
            'type'      => 2,
        ],
        [
            'id'        => 83,
            'parent_id' => 6,
            'name'      => '江门',
            'type'      => 2,
        ],
        [
            'id'        => 84,
            'parent_id' => 6,
            'name'      => '揭阳',
            'type'      => 2,
        ],
        [
            'id'        => 85,
            'parent_id' => 6,
            'name'      => '茂名',
            'type'      => 2,
        ],
        [
            'id'        => 86,
            'parent_id' => 6,
            'name'      => '梅州',
            'type'      => 2,
        ],
        [
            'id'        => 87,
            'parent_id' => 6,
            'name'      => '清远',
            'type'      => 2,
        ],
        [
            'id'        => 88,
            'parent_id' => 6,
            'name'      => '汕头',
            'type'      => 2,
        ],
        [
            'id'        => 89,
            'parent_id' => 6,
            'name'      => '汕尾',
            'type'      => 2,
        ],
        [
            'id'        => 90,
            'parent_id' => 6,
            'name'      => '韶关',
            'type'      => 2,
        ],
        [
            'id'        => 91,
            'parent_id' => 6,
            'name'      => '阳江',
            'type'      => 2,
        ],
        [
            'id'        => 92,
            'parent_id' => 6,
            'name'      => '云浮',
            'type'      => 2,
        ],
        [
            'id'        => 93,
            'parent_id' => 6,
            'name'      => '湛江',
            'type'      => 2,
        ],
        [
            'id'        => 94,
            'parent_id' => 6,
            'name'      => '肇庆',
            'type'      => 2,
        ],
        [
            'id'        => 95,
            'parent_id' => 6,
            'name'      => '中山',
            'type'      => 2,
        ],
        [
            'id'        => 96,
            'parent_id' => 6,
            'name'      => '珠海',
            'type'      => 2,
        ],
        [
            'id'        => 97,
            'parent_id' => 7,
            'name'      => '南宁',
            'type'      => 2,
        ],
        [
            'id'        => 98,
            'parent_id' => 7,
            'name'      => '桂林',
            'type'      => 2,
        ],
        [
            'id'        => 99,
            'parent_id' => 7,
            'name'      => '百色',
            'type'      => 2,
        ],
        [
            'id'        => 100,
            'parent_id' => 7,
            'name'      => '北海',
            'type'      => 2,
        ],
        [
            'id'        => 101,
            'parent_id' => 7,
            'name'      => '崇左',
            'type'      => 2,
        ],
        [
            'id'        => 102,
            'parent_id' => 7,
            'name'      => '防城港',
            'type'      => 2,
        ],
        [
            'id'        => 103,
            'parent_id' => 7,
            'name'      => '贵港',
            'type'      => 2,
        ],
        [
            'id'        => 104,
            'parent_id' => 7,
            'name'      => '河池',
            'type'      => 2,
        ],
        [
            'id'        => 105,
            'parent_id' => 7,
            'name'      => '贺州',
            'type'      => 2,
        ],
        [
            'id'        => 106,
            'parent_id' => 7,
            'name'      => '来宾',
            'type'      => 2,
        ],
        [
            'id'        => 107,
            'parent_id' => 7,
            'name'      => '柳州',
            'type'      => 2,
        ],
        [
            'id'        => 108,
            'parent_id' => 7,
            'name'      => '钦州',
            'type'      => 2,
        ],
        [
            'id'        => 109,
            'parent_id' => 7,
            'name'      => '梧州',
            'type'      => 2,
        ],
        [
            'id'        => 110,
            'parent_id' => 7,
            'name'      => '玉林',
            'type'      => 2,
        ],
        [
            'id'        => 111,
            'parent_id' => 8,
            'name'      => '贵阳',
            'type'      => 2,
        ],
        [
            'id'        => 112,
            'parent_id' => 8,
            'name'      => '安顺',
            'type'      => 2,
        ],
        [
            'id'        => 113,
            'parent_id' => 8,
            'name'      => '毕节',
            'type'      => 2,
        ],
        [
            'id'        => 114,
            'parent_id' => 8,
            'name'      => '六盘水',
            'type'      => 2,
        ],
        [
            'id'        => 115,
            'parent_id' => 8,
            'name'      => '黔东南',
            'type'      => 2,
        ],
        [
            'id'        => 116,
            'parent_id' => 8,
            'name'      => '黔南',
            'type'      => 2,
        ],
        [
            'id'        => 117,
            'parent_id' => 8,
            'name'      => '黔西南',
            'type'      => 2,
        ],
        [
            'id'        => 118,
            'parent_id' => 8,
            'name'      => '铜仁',
            'type'      => 2,
        ],
        [
            'id'        => 119,
            'parent_id' => 8,
            'name'      => '遵义',
            'type'      => 2,
        ],
        [
            'id'        => 120,
            'parent_id' => 9,
            'name'      => '海口',
            'type'      => 2,
        ],
        [
            'id'        => 121,
            'parent_id' => 9,
            'name'      => '三亚',
            'type'      => 2,
        ],
        [
            'id'        => 122,
            'parent_id' => 9,
            'name'      => '白沙',
            'type'      => 2,
        ],
        [
            'id'        => 123,
            'parent_id' => 9,
            'name'      => '保亭',
            'type'      => 2,
        ],
        [
            'id'        => 124,
            'parent_id' => 9,
            'name'      => '昌江',
            'type'      => 2,
        ],
        [
            'id'        => 125,
            'parent_id' => 9,
            'name'      => '澄迈县',
            'type'      => 2,
        ],
        [
            'id'        => 126,
            'parent_id' => 9,
            'name'      => '定安县',
            'type'      => 2,
        ],
        [
            'id'        => 127,
            'parent_id' => 9,
            'name'      => '东方',
            'type'      => 2,
        ],
        [
            'id'        => 128,
            'parent_id' => 9,
            'name'      => '乐东',
            'type'      => 2,
        ],
        [
            'id'        => 129,
            'parent_id' => 9,
            'name'      => '临高县',
            'type'      => 2,
        ],
        [
            'id'        => 130,
            'parent_id' => 9,
            'name'      => '陵水',
            'type'      => 2,
        ],
        [
            'id'        => 131,
            'parent_id' => 9,
            'name'      => '琼海',
            'type'      => 2,
        ],
        [
            'id'        => 132,
            'parent_id' => 9,
            'name'      => '琼中',
            'type'      => 2,
        ],
        [
            'id'        => 133,
            'parent_id' => 9,
            'name'      => '屯昌县',
            'type'      => 2,
        ],
        [
            'id'        => 134,
            'parent_id' => 9,
            'name'      => '万宁',
            'type'      => 2,
        ],
        [
            'id'        => 135,
            'parent_id' => 9,
            'name'      => '文昌',
            'type'      => 2,
        ],
        [
            'id'        => 136,
            'parent_id' => 9,
            'name'      => '五指山',
            'type'      => 2,
        ],
        [
            'id'        => 137,
            'parent_id' => 9,
            'name'      => '儋州',
            'type'      => 2,
        ],
        [
            'id'        => 138,
            'parent_id' => 10,
            'name'      => '石家庄',
            'type'      => 2,
        ],
        [
            'id'        => 139,
            'parent_id' => 10,
            'name'      => '保定',
            'type'      => 2,
        ],
        [
            'id'        => 140,
            'parent_id' => 10,
            'name'      => '沧州',
            'type'      => 2,
        ],
        [
            'id'        => 141,
            'parent_id' => 10,
            'name'      => '承德',
            'type'      => 2,
        ],
        [
            'id'        => 142,
            'parent_id' => 10,
            'name'      => '邯郸',
            'type'      => 2,
        ],
        [
            'id'        => 143,
            'parent_id' => 10,
            'name'      => '衡水',
            'type'      => 2,
        ],
        [
            'id'        => 144,
            'parent_id' => 10,
            'name'      => '廊坊',
            'type'      => 2,
        ],
        [
            'id'        => 145,
            'parent_id' => 10,
            'name'      => '秦皇岛',
            'type'      => 2,
        ],
        [
            'id'        => 146,
            'parent_id' => 10,
            'name'      => '唐山',
            'type'      => 2,
        ],
        [
            'id'        => 147,
            'parent_id' => 10,
            'name'      => '邢台',
            'type'      => 2,
        ],
        [
            'id'        => 148,
            'parent_id' => 10,
            'name'      => '张家口',
            'type'      => 2,
        ],
        [
            'id'        => 149,
            'parent_id' => 11,
            'name'      => '郑州',
            'type'      => 2,
        ],
        [
            'id'        => 150,
            'parent_id' => 11,
            'name'      => '洛阳',
            'type'      => 2,
        ],
        [
            'id'        => 151,
            'parent_id' => 11,
            'name'      => '开封',
            'type'      => 2,
        ],
        [
            'id'        => 152,
            'parent_id' => 11,
            'name'      => '安阳',
            'type'      => 2,
        ],
        [
            'id'        => 153,
            'parent_id' => 11,
            'name'      => '鹤壁',
            'type'      => 2,
        ],
        [
            'id'        => 154,
            'parent_id' => 11,
            'name'      => '济源',
            'type'      => 2,
        ],
        [
            'id'        => 155,
            'parent_id' => 11,
            'name'      => '焦作',
            'type'      => 2,
        ],
        [
            'id'        => 156,
            'parent_id' => 11,
            'name'      => '南阳',
            'type'      => 2,
        ],
        [
            'id'        => 157,
            'parent_id' => 11,
            'name'      => '平顶山',
            'type'      => 2,
        ],
        [
            'id'        => 158,
            'parent_id' => 11,
            'name'      => '三门峡',
            'type'      => 2,
        ],
        [
            'id'        => 159,
            'parent_id' => 11,
            'name'      => '商丘',
            'type'      => 2,
        ],
        [
            'id'        => 160,
            'parent_id' => 11,
            'name'      => '新乡',
            'type'      => 2,
        ],
        [
            'id'        => 161,
            'parent_id' => 11,
            'name'      => '信阳',
            'type'      => 2,
        ],
        [
            'id'        => 162,
            'parent_id' => 11,
            'name'      => '许昌',
            'type'      => 2,
        ],
        [
            'id'        => 163,
            'parent_id' => 11,
            'name'      => '周口',
            'type'      => 2,
        ],
        [
            'id'        => 164,
            'parent_id' => 11,
            'name'      => '驻马店',
            'type'      => 2,
        ],
        [
            'id'        => 165,
            'parent_id' => 11,
            'name'      => '漯河',
            'type'      => 2,
        ],
        [
            'id'        => 166,
            'parent_id' => 11,
            'name'      => '濮阳',
            'type'      => 2,
        ],
        [
            'id'        => 167,
            'parent_id' => 12,
            'name'      => '哈尔滨',
            'type'      => 2,
        ],
        [
            'id'        => 168,
            'parent_id' => 12,
            'name'      => '大庆',
            'type'      => 2,
        ],
        [
            'id'        => 169,
            'parent_id' => 12,
            'name'      => '大兴安岭',
            'type'      => 2,
        ],
        [
            'id'        => 170,
            'parent_id' => 12,
            'name'      => '鹤岗',
            'type'      => 2,
        ],
        [
            'id'        => 171,
            'parent_id' => 12,
            'name'      => '黑河',
            'type'      => 2,
        ],
        [
            'id'        => 172,
            'parent_id' => 12,
            'name'      => '鸡西',
            'type'      => 2,
        ],
        [
            'id'        => 173,
            'parent_id' => 12,
            'name'      => '佳木斯',
            'type'      => 2,
        ],
        [
            'id'        => 174,
            'parent_id' => 12,
            'name'      => '牡丹江',
            'type'      => 2,
        ],
        [
            'id'        => 175,
            'parent_id' => 12,
            'name'      => '七台河',
            'type'      => 2,
        ],
        [
            'id'        => 176,
            'parent_id' => 12,
            'name'      => '齐齐哈尔',
            'type'      => 2,
        ],
        [
            'id'        => 177,
            'parent_id' => 12,
            'name'      => '双鸭山',
            'type'      => 2,
        ],
        [
            'id'        => 178,
            'parent_id' => 12,
            'name'      => '绥化',
            'type'      => 2,
        ],
        [
            'id'        => 179,
            'parent_id' => 12,
            'name'      => '伊春',
            'type'      => 2,
        ],
        [
            'id'        => 180,
            'parent_id' => 13,
            'name'      => '武汉',
            'type'      => 2,
        ],
        [
            'id'        => 181,
            'parent_id' => 13,
            'name'      => '仙桃',
            'type'      => 2,
        ],
        [
            'id'        => 182,
            'parent_id' => 13,
            'name'      => '鄂州',
            'type'      => 2,
        ],
        [
            'id'        => 183,
            'parent_id' => 13,
            'name'      => '黄冈',
            'type'      => 2,
        ],
        [
            'id'        => 184,
            'parent_id' => 13,
            'name'      => '黄石',
            'type'      => 2,
        ],
        [
            'id'        => 185,
            'parent_id' => 13,
            'name'      => '荆门',
            'type'      => 2,
        ],
        [
            'id'        => 186,
            'parent_id' => 13,
            'name'      => '荆州',
            'type'      => 2,
        ],
        [
            'id'        => 187,
            'parent_id' => 13,
            'name'      => '潜江',
            'type'      => 2,
        ],
        [
            'id'        => 188,
            'parent_id' => 13,
            'name'      => '神农架林区',
            'type'      => 2,
        ],
        [
            'id'        => 189,
            'parent_id' => 13,
            'name'      => '十堰',
            'type'      => 2,
        ],
        [
            'id'        => 190,
            'parent_id' => 13,
            'name'      => '随州',
            'type'      => 2,
        ],
        [
            'id'        => 191,
            'parent_id' => 13,
            'name'      => '天门',
            'type'      => 2,
        ],
        [
            'id'        => 192,
            'parent_id' => 13,
            'name'      => '咸宁',
            'type'      => 2,
        ],
        [
            'id'        => 193,
            'parent_id' => 13,
            'name'      => '襄樊',
            'type'      => 2,
        ],
        [
            'id'        => 194,
            'parent_id' => 13,
            'name'      => '孝感',
            'type'      => 2,
        ],
        [
            'id'        => 195,
            'parent_id' => 13,
            'name'      => '宜昌',
            'type'      => 2,
        ],
        [
            'id'        => 196,
            'parent_id' => 13,
            'name'      => '恩施',
            'type'      => 2,
        ],
        [
            'id'        => 197,
            'parent_id' => 14,
            'name'      => '长沙',
            'type'      => 2,
        ],
        [
            'id'        => 198,
            'parent_id' => 14,
            'name'      => '张家界',
            'type'      => 2,
        ],
        [
            'id'        => 199,
            'parent_id' => 14,
            'name'      => '常德',
            'type'      => 2,
        ],
        [
            'id'        => 200,
            'parent_id' => 14,
            'name'      => '郴州',
            'type'      => 2,
        ],
        [
            'id'        => 201,
            'parent_id' => 14,
            'name'      => '衡阳',
            'type'      => 2,
        ],
        [
            'id'        => 202,
            'parent_id' => 14,
            'name'      => '怀化',
            'type'      => 2,
        ],
        [
            'id'        => 203,
            'parent_id' => 14,
            'name'      => '娄底',
            'type'      => 2,
        ],
        [
            'id'        => 204,
            'parent_id' => 14,
            'name'      => '邵阳',
            'type'      => 2,
        ],
        [
            'id'        => 205,
            'parent_id' => 14,
            'name'      => '湘潭',
            'type'      => 2,
        ],
        [
            'id'        => 206,
            'parent_id' => 14,
            'name'      => '湘西',
            'type'      => 2,
        ],
        [
            'id'        => 207,
            'parent_id' => 14,
            'name'      => '益阳',
            'type'      => 2,
        ],
        [
            'id'        => 208,
            'parent_id' => 14,
            'name'      => '永州',
            'type'      => 2,
        ],
        [
            'id'        => 209,
            'parent_id' => 14,
            'name'      => '岳阳',
            'type'      => 2,
        ],
        [
            'id'        => 210,
            'parent_id' => 14,
            'name'      => '株洲',
            'type'      => 2,
        ],
        [
            'id'        => 211,
            'parent_id' => 15,
            'name'      => '长春',
            'type'      => 2,
        ],
        [
            'id'        => 212,
            'parent_id' => 15,
            'name'      => '吉林',
            'type'      => 2,
        ],
        [
            'id'        => 213,
            'parent_id' => 15,
            'name'      => '白城',
            'type'      => 2,
        ],
        [
            'id'        => 214,
            'parent_id' => 15,
            'name'      => '白山',
            'type'      => 2,
        ],
        [
            'id'        => 215,
            'parent_id' => 15,
            'name'      => '辽源',
            'type'      => 2,
        ],
        [
            'id'        => 216,
            'parent_id' => 15,
            'name'      => '四平',
            'type'      => 2,
        ],
        [
            'id'        => 217,
            'parent_id' => 15,
            'name'      => '松原',
            'type'      => 2,
        ],
        [
            'id'        => 218,
            'parent_id' => 15,
            'name'      => '通化',
            'type'      => 2,
        ],
        [
            'id'        => 219,
            'parent_id' => 15,
            'name'      => '延边',
            'type'      => 2,
        ],
        [
            'id'        => 220,
            'parent_id' => 16,
            'name'      => '南京',
            'type'      => 2,
        ],
        [
            'id'        => 221,
            'parent_id' => 16,
            'name'      => '苏州',
            'type'      => 2,
        ],
        [
            'id'        => 222,
            'parent_id' => 16,
            'name'      => '无锡',
            'type'      => 2,
        ],
        [
            'id'        => 223,
            'parent_id' => 16,
            'name'      => '常州',
            'type'      => 2,
        ],
        [
            'id'        => 224,
            'parent_id' => 16,
            'name'      => '淮安',
            'type'      => 2,
        ],
        [
            'id'        => 225,
            'parent_id' => 16,
            'name'      => '连云港',
            'type'      => 2,
        ],
        [
            'id'        => 226,
            'parent_id' => 16,
            'name'      => '南通',
            'type'      => 2,
        ],
        [
            'id'        => 227,
            'parent_id' => 16,
            'name'      => '宿迁',
            'type'      => 2,
        ],
        [
            'id'        => 228,
            'parent_id' => 16,
            'name'      => '泰州',
            'type'      => 2,
        ],
        [
            'id'        => 229,
            'parent_id' => 16,
            'name'      => '徐州',
            'type'      => 2,
        ],
        [
            'id'        => 230,
            'parent_id' => 16,
            'name'      => '盐城',
            'type'      => 2,
        ],
        [
            'id'        => 231,
            'parent_id' => 16,
            'name'      => '扬州',
            'type'      => 2,
        ],
        [
            'id'        => 232,
            'parent_id' => 16,
            'name'      => '镇江',
            'type'      => 2,
        ],
        [
            'id'        => 233,
            'parent_id' => 17,
            'name'      => '南昌',
            'type'      => 2,
        ],
        [
            'id'        => 234,
            'parent_id' => 17,
            'name'      => '抚州',
            'type'      => 2,
        ],
        [
            'id'        => 235,
            'parent_id' => 17,
            'name'      => '赣州',
            'type'      => 2,
        ],
        [
            'id'        => 236,
            'parent_id' => 17,
            'name'      => '吉安',
            'type'      => 2,
        ],
        [
            'id'        => 237,
            'parent_id' => 17,
            'name'      => '景德镇',
            'type'      => 2,
        ],
        [
            'id'        => 238,
            'parent_id' => 17,
            'name'      => '九江',
            'type'      => 2,
        ],
        [
            'id'        => 239,
            'parent_id' => 17,
            'name'      => '萍乡',
            'type'      => 2,
        ],
        [
            'id'        => 240,
            'parent_id' => 17,
            'name'      => '上饶',
            'type'      => 2,
        ],
        [
            'id'        => 241,
            'parent_id' => 17,
            'name'      => '新余',
            'type'      => 2,
        ],
        [
            'id'        => 242,
            'parent_id' => 17,
            'name'      => '宜春',
            'type'      => 2,
        ],
        [
            'id'        => 243,
            'parent_id' => 17,
            'name'      => '鹰潭',
            'type'      => 2,
        ],
        [
            'id'        => 244,
            'parent_id' => 18,
            'name'      => '沈阳',
            'type'      => 2,
        ],
        [
            'id'        => 245,
            'parent_id' => 18,
            'name'      => '大连',
            'type'      => 2,
        ],
        [
            'id'        => 246,
            'parent_id' => 18,
            'name'      => '鞍山',
            'type'      => 2,
        ],
        [
            'id'        => 247,
            'parent_id' => 18,
            'name'      => '本溪',
            'type'      => 2,
        ],
        [
            'id'        => 248,
            'parent_id' => 18,
            'name'      => '朝阳',
            'type'      => 2,
        ],
        [
            'id'        => 249,
            'parent_id' => 18,
            'name'      => '丹东',
            'type'      => 2,
        ],
        [
            'id'        => 250,
            'parent_id' => 18,
            'name'      => '抚顺',
            'type'      => 2,
        ],
        [
            'id'        => 251,
            'parent_id' => 18,
            'name'      => '阜新',
            'type'      => 2,
        ],
        [
            'id'        => 252,
            'parent_id' => 18,
            'name'      => '葫芦岛',
            'type'      => 2,
        ],
        [
            'id'        => 253,
            'parent_id' => 18,
            'name'      => '锦州',
            'type'      => 2,
        ],
        [
            'id'        => 254,
            'parent_id' => 18,
            'name'      => '辽阳',
            'type'      => 2,
        ],
        [
            'id'        => 255,
            'parent_id' => 18,
            'name'      => '盘锦',
            'type'      => 2,
        ],
        [
            'id'        => 256,
            'parent_id' => 18,
            'name'      => '铁岭',
            'type'      => 2,
        ],
        [
            'id'        => 257,
            'parent_id' => 18,
            'name'      => '营口',
            'type'      => 2,
        ],
        [
            'id'        => 258,
            'parent_id' => 19,
            'name'      => '呼和浩特',
            'type'      => 2,
        ],
        [
            'id'        => 259,
            'parent_id' => 19,
            'name'      => '阿拉善盟',
            'type'      => 2,
        ],
        [
            'id'        => 260,
            'parent_id' => 19,
            'name'      => '巴彦淖尔盟',
            'type'      => 2,
        ],
        [
            'id'        => 261,
            'parent_id' => 19,
            'name'      => '包头',
            'type'      => 2,
        ],
        [
            'id'        => 262,
            'parent_id' => 19,
            'name'      => '赤峰',
            'type'      => 2,
        ],
        [
            'id'        => 263,
            'parent_id' => 19,
            'name'      => '鄂尔多斯',
            'type'      => 2,
        ],
        [
            'id'        => 264,
            'parent_id' => 19,
            'name'      => '呼伦贝尔',
            'type'      => 2,
        ],
        [
            'id'        => 265,
            'parent_id' => 19,
            'name'      => '通辽',
            'type'      => 2,
        ],
        [
            'id'        => 266,
            'parent_id' => 19,
            'name'      => '乌海',
            'type'      => 2,
        ],
        [
            'id'        => 267,
            'parent_id' => 19,
            'name'      => '乌兰察布市',
            'type'      => 2,
        ],
        [
            'id'        => 268,
            'parent_id' => 19,
            'name'      => '锡林郭勒盟',
            'type'      => 2,
        ],
        [
            'id'        => 269,
            'parent_id' => 19,
            'name'      => '兴安盟',
            'type'      => 2,
        ],
        [
            'id'        => 270,
            'parent_id' => 20,
            'name'      => '银川',
            'type'      => 2,
        ],
        [
            'id'        => 271,
            'parent_id' => 20,
            'name'      => '固原',
            'type'      => 2,
        ],
        [
            'id'        => 272,
            'parent_id' => 20,
            'name'      => '石嘴山',
            'type'      => 2,
        ],
        [
            'id'        => 273,
            'parent_id' => 20,
            'name'      => '吴忠',
            'type'      => 2,
        ],
        [
            'id'        => 274,
            'parent_id' => 20,
            'name'      => '中卫',
            'type'      => 2,
        ],
        [
            'id'        => 275,
            'parent_id' => 21,
            'name'      => '西宁',
            'type'      => 2,
        ],
        [
            'id'        => 276,
            'parent_id' => 21,
            'name'      => '果洛',
            'type'      => 2,
        ],
        [
            'id'        => 277,
            'parent_id' => 21,
            'name'      => '海北',
            'type'      => 2,
        ],
        [
            'id'        => 278,
            'parent_id' => 21,
            'name'      => '海东',
            'type'      => 2,
        ],
        [
            'id'        => 279,
            'parent_id' => 21,
            'name'      => '海南',
            'type'      => 2,
        ],
        [
            'id'        => 280,
            'parent_id' => 21,
            'name'      => '海西',
            'type'      => 2,
        ],
        [
            'id'        => 281,
            'parent_id' => 21,
            'name'      => '黄南',
            'type'      => 2,
        ],
        [
            'id'        => 282,
            'parent_id' => 21,
            'name'      => '玉树',
            'type'      => 2,
        ],
        [
            'id'        => 283,
            'parent_id' => 22,
            'name'      => '济南',
            'type'      => 2,
        ],
        [
            'id'        => 284,
            'parent_id' => 22,
            'name'      => '青岛',
            'type'      => 2,
        ],
        [
            'id'        => 285,
            'parent_id' => 22,
            'name'      => '滨州',
            'type'      => 2,
        ],
        [
            'id'        => 286,
            'parent_id' => 22,
            'name'      => '德州',
            'type'      => 2,
        ],
        [
            'id'        => 287,
            'parent_id' => 22,
            'name'      => '东营',
            'type'      => 2,
        ],
        [
            'id'        => 288,
            'parent_id' => 22,
            'name'      => '菏泽',
            'type'      => 2,
        ],
        [
            'id'        => 289,
            'parent_id' => 22,
            'name'      => '济宁',
            'type'      => 2,
        ],
        [
            'id'        => 290,
            'parent_id' => 22,
            'name'      => '莱芜',
            'type'      => 2,
        ],
        [
            'id'        => 291,
            'parent_id' => 22,
            'name'      => '聊城',
            'type'      => 2,
        ],
        [
            'id'        => 292,
            'parent_id' => 22,
            'name'      => '临沂',
            'type'      => 2,
        ],
        [
            'id'        => 293,
            'parent_id' => 22,
            'name'      => '日照',
            'type'      => 2,
        ],
        [
            'id'        => 294,
            'parent_id' => 22,
            'name'      => '泰安',
            'type'      => 2,
        ],
        [
            'id'        => 295,
            'parent_id' => 22,
            'name'      => '威海',
            'type'      => 2,
        ],
        [
            'id'        => 296,
            'parent_id' => 22,
            'name'      => '潍坊',
            'type'      => 2,
        ],
        [
            'id'        => 297,
            'parent_id' => 22,
            'name'      => '烟台',
            'type'      => 2,
        ],
        [
            'id'        => 298,
            'parent_id' => 22,
            'name'      => '枣庄',
            'type'      => 2,
        ],
        [
            'id'        => 299,
            'parent_id' => 22,
            'name'      => '淄博',
            'type'      => 2,
        ],
        [
            'id'        => 300,
            'parent_id' => 23,
            'name'      => '太原',
            'type'      => 2,
        ],
        [
            'id'        => 301,
            'parent_id' => 23,
            'name'      => '长治',
            'type'      => 2,
        ],
        [
            'id'        => 302,
            'parent_id' => 23,
            'name'      => '大同',
            'type'      => 2,
        ],
        [
            'id'        => 303,
            'parent_id' => 23,
            'name'      => '晋城',
            'type'      => 2,
        ],
        [
            'id'        => 304,
            'parent_id' => 23,
            'name'      => '晋中',
            'type'      => 2,
        ],
        [
            'id'        => 305,
            'parent_id' => 23,
            'name'      => '临汾',
            'type'      => 2,
        ],
        [
            'id'        => 306,
            'parent_id' => 23,
            'name'      => '吕梁',
            'type'      => 2,
        ],
        [
            'id'        => 307,
            'parent_id' => 23,
            'name'      => '朔州',
            'type'      => 2,
        ],
        [
            'id'        => 308,
            'parent_id' => 23,
            'name'      => '忻州',
            'type'      => 2,
        ],
        [
            'id'        => 309,
            'parent_id' => 23,
            'name'      => '阳泉',
            'type'      => 2,
        ],
        [
            'id'        => 310,
            'parent_id' => 23,
            'name'      => '运城',
            'type'      => 2,
        ],
        [
            'id'        => 311,
            'parent_id' => 24,
            'name'      => '西安',
            'type'      => 2,
        ],
        [
            'id'        => 312,
            'parent_id' => 24,
            'name'      => '安康',
            'type'      => 2,
        ],
        [
            'id'        => 313,
            'parent_id' => 24,
            'name'      => '宝鸡',
            'type'      => 2,
        ],
        [
            'id'        => 314,
            'parent_id' => 24,
            'name'      => '汉中',
            'type'      => 2,
        ],
        [
            'id'        => 315,
            'parent_id' => 24,
            'name'      => '商洛',
            'type'      => 2,
        ],
        [
            'id'        => 316,
            'parent_id' => 24,
            'name'      => '铜川',
            'type'      => 2,
        ],
        [
            'id'        => 317,
            'parent_id' => 24,
            'name'      => '渭南',
            'type'      => 2,
        ],
        [
            'id'        => 318,
            'parent_id' => 24,
            'name'      => '咸阳',
            'type'      => 2,
        ],
        [
            'id'        => 319,
            'parent_id' => 24,
            'name'      => '延安',
            'type'      => 2,
        ],
        [
            'id'        => 320,
            'parent_id' => 24,
            'name'      => '榆林',
            'type'      => 2,
        ],
        [
            'id'        => 321,
            'parent_id' => 25,
            'name'      => '上海',
            'type'      => 2,
        ],
        [
            'id'        => 322,
            'parent_id' => 26,
            'name'      => '成都',
            'type'      => 2,
        ],
        [
            'id'        => 323,
            'parent_id' => 26,
            'name'      => '绵阳',
            'type'      => 2,
        ],
        [
            'id'        => 324,
            'parent_id' => 26,
            'name'      => '阿坝',
            'type'      => 2,
        ],
        [
            'id'        => 325,
            'parent_id' => 26,
            'name'      => '巴中',
            'type'      => 2,
        ],
        [
            'id'        => 326,
            'parent_id' => 26,
            'name'      => '达州',
            'type'      => 2,
        ],
        [
            'id'        => 327,
            'parent_id' => 26,
            'name'      => '德阳',
            'type'      => 2,
        ],
        [
            'id'        => 328,
            'parent_id' => 26,
            'name'      => '甘孜',
            'type'      => 2,
        ],
        [
            'id'        => 329,
            'parent_id' => 26,
            'name'      => '广安',
            'type'      => 2,
        ],
        [
            'id'        => 330,
            'parent_id' => 26,
            'name'      => '广元',
            'type'      => 2,
        ],
        [
            'id'        => 331,
            'parent_id' => 26,
            'name'      => '乐山',
            'type'      => 2,
        ],
        [
            'id'        => 332,
            'parent_id' => 26,
            'name'      => '凉山',
            'type'      => 2,
        ],
        [
            'id'        => 333,
            'parent_id' => 26,
            'name'      => '眉山',
            'type'      => 2,
        ],
        [
            'id'        => 334,
            'parent_id' => 26,
            'name'      => '南充',
            'type'      => 2,
        ],
        [
            'id'        => 335,
            'parent_id' => 26,
            'name'      => '内江',
            'type'      => 2,
        ],
        [
            'id'        => 336,
            'parent_id' => 26,
            'name'      => '攀枝花',
            'type'      => 2,
        ],
        [
            'id'        => 337,
            'parent_id' => 26,
            'name'      => '遂宁',
            'type'      => 2,
        ],
        [
            'id'        => 338,
            'parent_id' => 26,
            'name'      => '雅安',
            'type'      => 2,
        ],
        [
            'id'        => 339,
            'parent_id' => 26,
            'name'      => '宜宾',
            'type'      => 2,
        ],
        [
            'id'        => 340,
            'parent_id' => 26,
            'name'      => '资阳',
            'type'      => 2,
        ],
        [
            'id'        => 341,
            'parent_id' => 26,
            'name'      => '自贡',
            'type'      => 2,
        ],
        [
            'id'        => 342,
            'parent_id' => 26,
            'name'      => '泸州',
            'type'      => 2,
        ],
        [
            'id'        => 343,
            'parent_id' => 27,
            'name'      => '天津',
            'type'      => 2,
        ],
        [
            'id'        => 344,
            'parent_id' => 28,
            'name'      => '拉萨',
            'type'      => 2,
        ],
        [
            'id'        => 345,
            'parent_id' => 28,
            'name'      => '阿里',
            'type'      => 2,
        ],
        [
            'id'        => 346,
            'parent_id' => 28,
            'name'      => '昌都',
            'type'      => 2,
        ],
        [
            'id'        => 347,
            'parent_id' => 28,
            'name'      => '林芝',
            'type'      => 2,
        ],
        [
            'id'        => 348,
            'parent_id' => 28,
            'name'      => '那曲',
            'type'      => 2,
        ],
        [
            'id'        => 349,
            'parent_id' => 28,
            'name'      => '日喀则',
            'type'      => 2,
        ],
        [
            'id'        => 350,
            'parent_id' => 28,
            'name'      => '山南',
            'type'      => 2,
        ],
        [
            'id'        => 351,
            'parent_id' => 29,
            'name'      => '乌鲁木齐',
            'type'      => 2,
        ],
        [
            'id'        => 352,
            'parent_id' => 29,
            'name'      => '阿克苏',
            'type'      => 2,
        ],
        [
            'id'        => 353,
            'parent_id' => 29,
            'name'      => '阿拉尔',
            'type'      => 2,
        ],
        [
            'id'        => 354,
            'parent_id' => 29,
            'name'      => '巴音郭楞',
            'type'      => 2,
        ],
        [
            'id'        => 355,
            'parent_id' => 29,
            'name'      => '博尔塔拉',
            'type'      => 2,
        ],
        [
            'id'        => 356,
            'parent_id' => 29,
            'name'      => '昌吉',
            'type'      => 2,
        ],
        [
            'id'        => 357,
            'parent_id' => 29,
            'name'      => '哈密',
            'type'      => 2,
        ],
        [
            'id'        => 358,
            'parent_id' => 29,
            'name'      => '和田',
            'type'      => 2,
        ],
        [
            'id'        => 359,
            'parent_id' => 29,
            'name'      => '喀什',
            'type'      => 2,
        ],
        [
            'id'        => 360,
            'parent_id' => 29,
            'name'      => '克拉玛依',
            'type'      => 2,
        ],
        [
            'id'        => 361,
            'parent_id' => 29,
            'name'      => '克孜勒苏',
            'type'      => 2,
        ],
        [
            'id'        => 362,
            'parent_id' => 29,
            'name'      => '石河子',
            'type'      => 2,
        ],
        [
            'id'        => 363,
            'parent_id' => 29,
            'name'      => '图木舒克',
            'type'      => 2,
        ],
        [
            'id'        => 364,
            'parent_id' => 29,
            'name'      => '吐鲁番',
            'type'      => 2,
        ],
        [
            'id'        => 365,
            'parent_id' => 29,
            'name'      => '五家渠',
            'type'      => 2,
        ],
        [
            'id'        => 366,
            'parent_id' => 29,
            'name'      => '伊犁',
            'type'      => 2,
        ],
        [
            'id'        => 367,
            'parent_id' => 30,
            'name'      => '昆明',
            'type'      => 2,
        ],
        [
            'id'        => 368,
            'parent_id' => 30,
            'name'      => '怒江',
            'type'      => 2,
        ],
        [
            'id'        => 369,
            'parent_id' => 30,
            'name'      => '普洱',
            'type'      => 2,
        ],
        [
            'id'        => 370,
            'parent_id' => 30,
            'name'      => '丽江',
            'type'      => 2,
        ],
        [
            'id'        => 371,
            'parent_id' => 30,
            'name'      => '保山',
            'type'      => 2,
        ],
        [
            'id'        => 372,
            'parent_id' => 30,
            'name'      => '楚雄',
            'type'      => 2,
        ],
        [
            'id'        => 373,
            'parent_id' => 30,
            'name'      => '大理',
            'type'      => 2,
        ],
        [
            'id'        => 374,
            'parent_id' => 30,
            'name'      => '德宏',
            'type'      => 2,
        ],
        [
            'id'        => 375,
            'parent_id' => 30,
            'name'      => '迪庆',
            'type'      => 2,
        ],
        [
            'id'        => 376,
            'parent_id' => 30,
            'name'      => '红河',
            'type'      => 2,
        ],
        [
            'id'        => 377,
            'parent_id' => 30,
            'name'      => '临沧',
            'type'      => 2,
        ],
        [
            'id'        => 378,
            'parent_id' => 30,
            'name'      => '曲靖',
            'type'      => 2,
        ],
        [
            'id'        => 379,
            'parent_id' => 30,
            'name'      => '文山',
            'type'      => 2,
        ],
        [
            'id'        => 380,
            'parent_id' => 30,
            'name'      => '西双版纳',
            'type'      => 2,
        ],
        [
            'id'        => 381,
            'parent_id' => 30,
            'name'      => '玉溪',
            'type'      => 2,
        ],
        [
            'id'        => 382,
            'parent_id' => 30,
            'name'      => '昭通',
            'type'      => 2,
        ],
        [
            'id'        => 383,
            'parent_id' => 31,
            'name'      => '杭州',
            'type'      => 2,
        ],
        [
            'id'        => 384,
            'parent_id' => 31,
            'name'      => '湖州',
            'type'      => 2,
        ],
        [
            'id'        => 385,
            'parent_id' => 31,
            'name'      => '嘉兴',
            'type'      => 2,
        ],
        [
            'id'        => 386,
            'parent_id' => 31,
            'name'      => '金华',
            'type'      => 2,
        ],
        [
            'id'        => 387,
            'parent_id' => 31,
            'name'      => '丽水',
            'type'      => 2,
        ],
        [
            'id'        => 388,
            'parent_id' => 31,
            'name'      => '宁波',
            'type'      => 2,
        ],
        [
            'id'        => 389,
            'parent_id' => 31,
            'name'      => '绍兴',
            'type'      => 2,
        ],
        [
            'id'        => 390,
            'parent_id' => 31,
            'name'      => '台州',
            'type'      => 2,
        ],
        [
            'id'        => 391,
            'parent_id' => 31,
            'name'      => '温州',
            'type'      => 2,
        ],
        [
            'id'        => 392,
            'parent_id' => 31,
            'name'      => '舟山',
            'type'      => 2,
        ],
        [
            'id'        => 393,
            'parent_id' => 31,
            'name'      => '衢州',
            'type'      => 2,
        ],
        [
            'id'        => 394,
            'parent_id' => 32,
            'name'      => '重庆',
            'type'      => 2,
        ],
        [
            'id'        => 395,
            'parent_id' => 33,
            'name'      => '香港',
            'type'      => 2,
        ],
        [
            'id'        => 396,
            'parent_id' => 34,
            'name'      => '澳门',
            'type'      => 2,
        ],
        [
            'id'        => 397,
            'parent_id' => 35,
            'name'      => '台湾',
            'type'      => 2,
        ],
        [
            'id'        => 398,
            'parent_id' => 3,
            'name'      => '合肥',
            'type'      => 2,
        ],
    ],
];